import 'dart:io';
import 'package:excel/excel.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../models/student_record.dart';

class ExportService {
  // ── Excel Export ────────────────────────────────────────────────────────────
  static Future<void> toExcel(GradeSummary summary, String sourceFileName) async {
    final excel = Excel.createExcel();
    final sheetName = 'Graded Results';
    final sheet = excel[sheetName];

    // Remove default sheet if different
    if (excel.sheets.containsKey('Sheet1')) {
      excel.delete('Sheet1');
    }

    // ── Header row ──────────────────────────────
    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#1E3A5F'),
      fontColorHex: ExcelColor.fromHexString('#FFFFFF'),
      horizontalAlign: HorizontalAlign.Center,
    );

    sheet.appendRow([
      TextCellValue('No.'),
      TextCellValue('Student Name'),
      TextCellValue('Total Marks'),
      TextCellValue('Grade'),
    ]);

    for (int c = 0; c < 4; c++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: 0))
          .cellStyle = headerStyle;
    }

    // ── Data rows ───────────────────────────────
    for (int i = 0; i < summary.students.length; i++) {
      final s = summary.students[i];
      final isEven = i % 2 == 1;

      sheet.appendRow([
        IntCellValue(i + 1),
        TextCellValue(s.name),
        DoubleCellValue(s.marks),
        TextCellValue(s.grade),
      ]);

      if (isEven) {
        final rowStyle = CellStyle(
          backgroundColorHex: ExcelColor.fromHexString('#F5F8FC'),
        );
        for (int c = 0; c < 4; c++) {
          sheet
              .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: i + 1))
              .cellStyle = rowStyle;
        }
      }
    }

    // ── Summary row ─────────────────────────────
    final summaryRowIdx = summary.students.length + 1;
    sheet.appendRow([
      TextCellValue(''),
      TextCellValue('Class Average'),
      DoubleCellValue(double.parse(summary.average.toStringAsFixed(2))),
      TextCellValue(StudentRecord.computeGrade(summary.average)),
    ]);
    for (int c = 0; c < 4; c++) {
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: summaryRowIdx))
          .cellStyle = CellStyle(
        bold: true,
        backgroundColorHex: ExcelColor.fromHexString('#E8F0FA'),
      );
    }

    // ── Column widths ────────────────────────────
    sheet.setColumnWidth(0, 6);
    sheet.setColumnWidth(1, 30);
    sheet.setColumnWidth(2, 14);
    sheet.setColumnWidth(3, 10);

    // ── Save & share ─────────────────────────────
    final bytes = excel.save();
    if (bytes == null) throw Exception('Failed to encode Excel file.');

    final dir = await getTemporaryDirectory();
    final baseName = sourceFileName.replaceAll('.xlsx', '');
    final file = File('${dir.path}/${baseName}_graded.xlsx');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [
        XFile(
          file.path,
          mimeType:
              'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          name: '${baseName}_graded.xlsx',
        ),
      ],
      subject: 'Graded Results — $sourceFileName',
    );
  }

  // ── PDF Export ──────────────────────────────────────────────────────────────
  static Future<void> toPdf(GradeSummary summary, String sourceFileName) async {
    final doc = pw.Document(
      title: 'Student Grade Report',
      author: 'Student Grader App',
    );

    final gradeColorMap = {
      'A': PdfColor.fromHex('#00C896'),
      'B': PdfColor.fromHex('#4A90D9'),
      'C': PdfColor.fromHex('#F5A623'),
      'D': PdfColor.fromHex('#FF6B35'),
      'F': PdfColor.fromHex('#E84855'),
    };

    final dist = summary.distribution;
    final now = DateTime.now();
    final dateStr =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (ctx) => _buildPdfHeader(
          sourceFileName,
          dateStr,
          summary,
          dist,
          gradeColorMap,
          ctx.pageNumber == 1,
        ),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Student Grader App',
              style: pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey500,
              ),
            ),
            pw.Text(
              'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey500,
              ),
            ),
          ],
        ),
        build: (ctx) => [
          pw.TableHelper.fromTextArray(
            headers: ['#', 'Student Name', 'Marks', 'Grade'],
            data: summary.students.asMap().entries.map((e) {
              return [
                '${e.key + 1}',
                e.value.name,
                e.value.marks.toStringAsFixed(1),
                e.value.grade,
              ];
            }).toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
              fontSize: 11,
            ),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColor.fromInt(0xFF1E3A5F),
            ),
            oddRowDecoration: const pw.BoxDecoration(
              color: PdfColor.fromInt(0xFFF5F8FC),
            ),
            rowDecoration: const pw.BoxDecoration(color: PdfColors.white),
            cellStyle: pw.TextStyle(fontSize: 10),
            cellPadding: const pw.EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 8,
            ),
            columnWidths: {
              0: const pw.FixedColumnWidth(30),
              1: const pw.FlexColumnWidth(3),
              2: const pw.FixedColumnWidth(60),
              3: const pw.FixedColumnWidth(50),
            },
            cellAlignments: {
              0: pw.Alignment.center,
              1: pw.Alignment.centerLeft,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
            },
            border: pw.TableBorder.all(
              color: const PdfColor.fromInt(0xFFDDEAF5),
              width: 0.5,
            ),
            // Colour-code the Grade column cells
            cellDecoration: (index, data, rowNum) {
              if (index == 3 && rowNum > 0) {
                final grade = data.toString();
                final c = gradeColorMap[grade];
                if (c != null) {
                  return pw.BoxDecoration(
                    color: PdfColor(c.red, c.green, c.blue, 0.12),
                  );
                }
              }
              return null;
            },
          ),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename:
          '${sourceFileName.replaceAll('.xlsx', '')}_graded.pdf',
    );
  }

  static pw.Widget _buildPdfHeader(
    String fileName,
    String date,
    GradeSummary summary,
    Map<String, int> dist,
    Map<String, PdfColor> colorMap,
    bool isFirstPage,
  ) {
    if (!isFirstPage) return pw.SizedBox();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // Title bar
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          decoration: const pw.BoxDecoration(
            color: PdfColor.fromInt(0xFF1E3A5F),
            borderRadius: pw.BorderRadius.all(pw.Radius.circular(10)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Student Grade Report',
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text(
                    fileName,
                    style: const pw.TextStyle(
                      fontSize: 10,
                      color: PdfColor.fromInt(0xFFAABBCC),
                    ),
                  ),
                ],
              ),
              pw.Text(
                date,
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColor.fromInt(0xFFAABBCC),
                ),
              ),
            ],
          ),
        ),
        pw.SizedBox(height: 10),
        // Stats row
        pw.Row(
          children: [
            _statBox('Total Students', '${summary.students.length}'),
            pw.SizedBox(width: 8),
            _statBox('Class Average', '${summary.average.toStringAsFixed(1)}%'),
            pw.SizedBox(width: 8),
            _statBox('Pass Rate', '${summary.passRate.toStringAsFixed(1)}%'),
            pw.SizedBox(width: 8),
            _statBox('Top Score', '${summary.topScorer.marks.toStringAsFixed(1)}'),
          ],
        ),
        pw.SizedBox(height: 10),
        // Grade distribution
        pw.Row(
          children: dist.entries
              .where((e) => e.value > 0)
              .map((e) => pw.Padding(
                    padding: const pw.EdgeInsets.only(right: 6),
                    child: pw.Container(
                      padding: const pw.EdgeInsets.symmetric(
                          horizontal: 10, vertical: 4),
                      decoration: pw.BoxDecoration(
                        color: PdfColor(
                          colorMap[e.key]!.red,
                          colorMap[e.key]!.green,
                          colorMap[e.key]!.blue,
                          0.12,
                        ),
                        borderRadius:
                            const pw.BorderRadius.all(pw.Radius.circular(6)),
                        border: pw.Border.all(
                          color: PdfColor(
                            colorMap[e.key]!.red,
                            colorMap[e.key]!.green,
                            colorMap[e.key]!.blue,
                            0.4,
                          ),
                        ),
                      ),
                      child: pw.Text(
                        '${e.key}: ${e.value}',
                        style: pw.TextStyle(
                          fontSize: 9,
                          fontWeight: pw.FontWeight.bold,
                          color: colorMap[e.key],
                        ),
                      ),
                    ),
                  ))
              .toList(),
        ),
        pw.SizedBox(height: 14),
      ],
    );
  }

  static pw.Widget _statBox(String label, String value) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(8),
        decoration: const pw.BoxDecoration(
          color: PdfColor.fromInt(0xFFF5F8FC),
          borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
          border: pw.Border.fromBorderSide(
            pw.BorderSide(color: PdfColor.fromInt(0xFFDDEAF5)),
          ),
        ),
        child: pw.Column(
          children: [
            pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: const PdfColor.fromInt(0xFF1E3A5F),
              ),
            ),
            pw.Text(
              label,
              style: const pw.TextStyle(
                fontSize: 8,
                color: PdfColor.fromInt(0xFF8FA3B8),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
